In [3]:
import numpy as np

In [6]:
from sklearn.model_selection import train_test_split
#  sklearn.cross_validation has changed to sklearn.model_selection

In [7]:
X, y = np.arange(10).reshape((5,2)), range (5)

In [8]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
y

range(0, 5)

In [10]:
list(y)

[0, 1, 2, 3, 4]

In [11]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.3)

In [12]:
X_train

array([[8, 9],
       [0, 1],
       [4, 5]])

In [13]:
X_test

array([[2, 3],
       [6, 7]])

In [14]:
y_train

[4, 0, 2]

In [15]:
y_test

[1, 3]